/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EnquiryId = IDL.Nat;
export const Enquiry = IDL.Record({
  'id' : EnquiryId,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const EnquiryInput = IDL.Record({
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'listEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'submitEnquiry' : IDL.Func([EnquiryInput], [EnquiryId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EnquiryId = IDL.Nat;
  const Enquiry = IDL.Record({
    'id' : EnquiryId,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const EnquiryInput = IDL.Record({
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'listEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'submitEnquiry' : IDL.Func([EnquiryInput], [EnquiryId], []),
  });
};

export const init = ({ IDL }) => { return []; };